name: fatdoge_ci
on:
  push:
    branches: [ main ]
jobs:
  sync_branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@gwei
      - name: state step
        run: echo 'Merging main commits to gwei branch'
      - name: git merging
        run: |
          git switch gwei
          git merge main
          git commit -m "updated gwei with main commits"
          git push origin gwei
          
      - uses: actions/checkout@vouch
      - name: state step
        run: echo 'Merging main commits to vouch branch'
      - name: git merging
        run: |
          git switch vouch
          git merge main
          git commit -m "updated vouch with main commits"
          git push origin vouch
          
      - uses: actions/checkout@classes
      - name: state step
        run: echo 'Merging main commits to classes branch'
      - name: git merging
        run: |
          git switch classes
          git merge main
          git commit -m "updated classes with main commits"
          git push origin classes
